stages:
  - build
  #- test
  #- release

variables:
  IMG_BASE: registry.gitlab.com/digonio/images/hostyourdocs-base:c05cb9bb
  IMG_KANIKO: gcr.io/kaniko-project/executor:v1.9.0-debug
  CONTEXT_PATH: build_image/

####################################################################################################
### Build stage
####################################################################################################
build_doc:
  stage: build
  image:
    name: ${IMG_BASE}
  script:
    - pip install -e .[dev]
    - python -m sphinx -b html doc/ doc/_build/html
    - tar -C ./doc/_build/html -cpz . -f ./doc_build.tar.gz
    - >
      curl -X 'POST'
      'https://digon.io/hyd/api/v1/version/upload'
      -H 'accept: application/json'
      -H "Authorization: Bearer ${HYD_TOKEN}"
      -H 'Content-Type: multipart/form-data'
      -F 'file=@doc_build.tar.gz;type=application/gzip'
      -F 'project_id=1'
      -F "version=${CI_COMMIT_SHORT_SHA}"
    # - >
    #   curl -X 'POST'
    #     "https://digon.io/hyd/api/v1/tag/create?project_id=1&tag=${CI_COMMIT_TAG}&primary=false"
    #     -H 'accept: application/json'
    #     -H "Authorization: Bearer ${HYD_TOKEN}"
    #     -d ''
    - >
      curl -X 'PATCH'
      "https://digon.io/hyd/api/v1/tag/move?project_id=1&tag=${CI_COMMIT_BRANCH}&version=${CI_COMMIT_SHORT_SHA}"
      -H 'accept: application/json'
      -H "Authorization: Bearer ${HYD_TOKEN}"
  rules:
    - if: $CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "dev"

### Dev
build_image_dev:
  stage: build
  image:
    name: ${IMG_KANIKO}
    entrypoint: [""]
  script:
    - sh script/build_base.sh
    - >
      /kaniko/executor
      --context ${CONTEXT_PATH}
      --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}"
      --verbosity info
      --force
      --no-push
  rules:
    - if: $CI_COMMIT_TAG == null


### Release
build_image_tag:
  stage: build
  image:
    name: ${IMG_KANIKO}
    entrypoint: [""]
  script:
    # https://docs.gitlab.com/ee/ci/docker/using_kaniko.html
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"},\"$CI_DEPENDENCY_PROXY_SERVER\":{\"auth\":\"$(printf "%s:%s" ${CI_DEPENDENCY_PROXY_USER} "${CI_DEPENDENCY_PROXY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - sh script/build_base.sh
    - >
      /kaniko/executor
      --context ${CONTEXT_PATH}
      --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}"
      --verbosity info
      --force
  only:
    - tags

