repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort
        require_serial: true
        language: python
        language_version: python3
        types_or: [cython, pyi, python]
        args: ["--filter-files"]
      - id: black
        name: black
        description: "Black: The uncompromising Python code formatter"
        entry: black
        language: python
        minimum_pre_commit_version: 2.9.2
        require_serial: true
        types_or: [python, pyi]
        args: [--safe, --quiet]
      - id: sphinx
        name: sphinx
        entry: python
        language: system
        pass_filenames: false
        always_run: true
        args: [-m, sphinx, -b, html, doc/, doc/_build/html]