[tool.black]
line-length = 100
target-version = ['py310', 'py311']

[tool.isort]
py_version = 310
profile = "black"

[tool.pydocstyle]
convention = "numpy"
add-ignore = ["D105"]

[tool.mypy]
python_version = "3.10"
warn_return_any = true
warn_unused_configs = true
disallow_any_generics = true
disallow_subclassing_any = true
enable_recursive_aliases = true
plugins = "sqlalchemy.ext.mypy.plugin"

[tool.pytest.ini_options]
asyncio_mode = "strict"
